### ISSUE TITLE
Angular 10.X would build, version 12 build gets error

### ISSUE THREAD

**Issue by markhayton** [adriandavidbrand/ngx-ez#1]
ng build --ngx-ez

------------------------------------------------------------------------------
Building entry point 'ngx-ez'
------------------------------------------------------------------------------
✖ Compiling with Angular sources in Ivy full compilation mode.
ngx-ez/src/lib/ez-forms/validators/validator-base.directive.ts:9:18 - error NG2003: No suitable injection token for parameter 'inputs' of class 'ValidatorBaseDirective'.
  Consider using the @Inject decorator to specify an injection token.

9   constructor(...inputs: string[]) {
                   ~~~~~~

  ngx-ez/src/lib/ez-forms/validators/validator-base.directive.ts:9:26
    9   constructor(...inputs: string[]) {
                               ~~~~~~~~
    This type is not supported as injection token.

**Comment by adriandavidbrand** [comment]
The latest version has been upgraded to Angular 14
